export const CATEGORIES = [
  { id: 'all', label: 'All', emoji: '🛍️' },
  { id: 'street-food', label: 'Street Food', emoji: '🍢' },
  { id: 'jewellery', label: 'Jewellery', emoji: '💍' },
  { id: 'pottery', label: 'Pottery', emoji: '🏺' },
  { id: 'candles', label: 'Candles', emoji: '🕯️' },
  { id: 'art', label: 'Art & Posters', emoji: '🎨' },
  { id: 'handmade', label: 'Handmade', emoji: '🤲' },
  { id: 'clothing', label: 'Clothing', emoji: '👗' },
  { id: 'plants', label: 'Plants', emoji: '🌿' },
]

export const STALLS = [
  {
    id: 's1',
    name: "Meera's Candle Corner",
    vendorId: 'v1',
    category: 'candles',
    location: 'Connaught Place, Delhi',
    rating: 4.8,
    reviewCount: 124,
    distance: '1.2 km',
    image: 'https://images.unsplash.com/photo-1602607702065-d22cf19ae99c?w=400',
    tags: ['Handmade', 'Aromatic', 'Custom'],
    isOpen: true,
    deliveryTime: '2-3 days',
    minOrder: 150,
  },
  {
    id: 's2',
    name: "Raj's Pottery Works",
    vendorId: 'v2',
    category: 'pottery',
    location: 'Jaipur Haat, Delhi',
    rating: 4.6,
    reviewCount: 89,
    distance: '2.5 km',
    image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400',
    tags: ['Traditional', 'Custom Order'],
    isOpen: true,
    deliveryTime: '3-5 days',
    minOrder: 250,
  },
  {
    id: 's3',
    name: "Priya's Jewel Box",
    vendorId: 'v3',
    category: 'jewellery',
    location: 'Lajpat Nagar, Delhi',
    rating: 4.9,
    reviewCount: 203,
    distance: '0.8 km',
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400',
    tags: ['Silver', 'Gold Plated', 'Custom'],
    isOpen: false,
    deliveryTime: '1-2 days',
    minOrder: 300,
  },
  {
    id: 's4',
    name: 'Street Bites by Arjun',
    vendorId: 'v4',
    category: 'street-food',
    location: 'Chandni Chowk, Delhi',
    rating: 4.7,
    reviewCount: 512,
    distance: '3.1 km',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
    tags: ['Veg', 'Spicy', 'Fresh Daily'],
    isOpen: true,
    deliveryTime: '45 min',
    minOrder: 100,
  },
  {
    id: 's5',
    name: 'Canvas & Colors – Sunita',
    vendorId: 'v5',
    category: 'art',
    location: 'Hauz Khas Village, Delhi',
    rating: 4.5,
    reviewCount: 67,
    distance: '4.0 km',
    image: 'https://images.unsplash.com/photo-1579762715118-a6f1d4b934f1?w=400',
    tags: ['Original Art', 'Prints', 'Custom'],
    isOpen: true,
    deliveryTime: '5-7 days',
    minOrder: 500,
  },
  {
    id: 's6',
    name: 'Green Thumb Plants',
    vendorId: 'v6',
    category: 'plants',
    location: 'Mehrauli, Delhi',
    rating: 4.4,
    reviewCount: 44,
    distance: '5.2 km',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400',
    tags: ['Indoor', 'Succulents', 'Rare'],
    isOpen: true,
    deliveryTime: '1 day',
    minOrder: 200,
  },
]

export const PRODUCTS: Record<string, any[]> = {
  s1: [
    {
      id: 'p1',
      stallId: 's1',
      name: 'Lavender Dream Candle',
      price: 280,
      originalPrice: 350,
      image:
        'https://images.unsplash.com/photo-1572726729207-a78d6feb18d7?w=300',
      variants: ['Small', 'Medium', 'Large'],
      description: 'Hand-poured soy wax with real lavender buds.',
    },
    {
      id: 'p2',
      stallId: 's1',
      name: 'Rose & Sandalwood Candle',
      price: 320,
      originalPrice: null,
      image:
        'https://images.unsplash.com/photo-1602607702065-d22cf19ae99c?w=300',
      variants: ['Standard', 'Gift Box'],
      description: 'Perfect gift for loved ones.',
    },
    {
      id: 'p3',
      stallId: 's1',
      name: 'Custom Name Candle',
      price: 450,
      originalPrice: null,
      image: 'https://images.unsplash.com/photo-1543051932-6ef9fecfcb46?w=300',
      variants: [],
      description: 'Personalized with any name or message.',
    },
  ],
  s2: [
    {
      id: 'p4',
      stallId: 's2',
      name: 'Terracotta Mug',
      price: 180,
      originalPrice: 220,
      image:
        'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=300',
      variants: ['Natural', 'Painted'],
      description: 'Handcrafted terracotta mug.',
    },
    {
      id: 'p5',
      stallId: 's2',
      name: 'Flower Vase Set',
      price: 550,
      originalPrice: null,
      image:
        'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=300',
      variants: ['Small', 'Large', 'Set of 3'],
      description: 'Beautiful hand-painted vases.',
    },
  ],
  s3: [
    {
      id: 'p6',
      stallId: 's3',
      name: 'Oxidized Earrings',
      price: 199,
      originalPrice: 299,
      image:
        'https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=300',
      variants: ['Silver', 'Gold'],
      description: 'Trendy oxidized silver earrings.',
    },
    {
      id: 'p7',
      stallId: 's3',
      name: 'Beaded Anklet',
      price: 149,
      originalPrice: null,
      image:
        'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=300',
      variants: ['Single', 'Pair'],
      description: 'Handmade beaded anklet.',
    },
  ],
  s4: [
    {
      id: 'p8',
      stallId: 's4',
      name: 'Aloo Tikki Platter',
      price: 80,
      originalPrice: null,
      image:
        'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300',
      variants: ['4 pcs', '8 pcs'],
      description: 'Crispy aloo tikki with chutneys.',
    },
    {
      id: 'p9',
      stallId: 's4',
      name: 'Chaat Combo Box',
      price: 120,
      originalPrice: 150,
      image:
        'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=300',
      variants: ['Regular', 'Large'],
      description: 'Mix chaat combo for 2.',
    },
  ],
  s5: [
    {
      id: 'p10',
      stallId: 's5',
      name: 'Watercolor Landscape Print',
      price: 650,
      originalPrice: 800,
      image:
        'https://images.unsplash.com/photo-1579762715118-a6f1d4b934f1?w=300',
      variants: ['A4', 'A3'],
      description: 'Beautiful watercolor landscape.',
    },
    {
      id: 'p11',
      stallId: 's5',
      name: 'Custom Portrait',
      price: 1200,
      originalPrice: null,
      image:
        'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=300',
      variants: [],
      description: 'Hand-drawn portrait from your photo.',
    },
  ],
  s6: [
    {
      id: 'p12',
      stallId: 's6',
      name: 'Succulent Trio',
      price: 299,
      originalPrice: 399,
      image:
        'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=300',
      variants: ['With pot', 'Without pot'],
      description: 'Set of 3 mini succulents.',
    },
    {
      id: 'p13',
      stallId: 's6',
      name: 'Money Plant',
      price: 149,
      originalPrice: null,
      image:
        'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=300',
      variants: ['Small', 'Medium'],
      description: 'Classic money plant in a ceramic pot.',
    },
  ],
}

export const TIME_SLOTS = [
  '9:00 AM - 11:00 AM',
  '11:00 AM - 1:00 PM',
  '1:00 PM - 3:00 PM',
  '3:00 PM - 5:00 PM',
  '5:00 PM - 7:00 PM',
]

export const MOCK_ORDERS = [
  {
    id: 'o1',
    product: 'Lavender Dream Candle',
    customer: 'Ananya S.',
    variant: 'Medium',
    qty: 2,
    total: 560,
    status: 'pending',
    time: '10 min ago',
    type: 'preorder',
    slot: '3:00 PM - 5:00 PM',
  },
  {
    id: 'o2',
    product: 'Custom Name Candle',
    customer: 'Rohit M.',
    variant: '-',
    qty: 1,
    total: 450,
    status: 'processing',
    time: '1 hr ago',
    type: 'immediate',
    slot: 'ASAP',
  },
  {
    id: 'o3',
    product: 'Rose & Sandalwood Candle',
    customer: 'Priya K.',
    variant: 'Gift Box',
    qty: 3,
    total: 960,
    status: 'ready',
    time: '3 hrs ago',
    type: 'preorder',
    slot: '11:00 AM - 1:00 PM',
  },
  {
    id: 'o4',
    product: 'Lavender Dream Candle',
    customer: 'Dev R.',
    variant: 'Small',
    qty: 1,
    total: 280,
    status: 'delivered',
    time: 'Yesterday',
    type: 'immediate',
    slot: 'ASAP',
  },
]
