export const CATEGORIES = [
  { id: 'all', label: 'All', emoji: '🛍️' },
  { id: 'street-food', label: 'Street Food', emoji: '🍢' },
  { id: 'jewellery', label: 'Jewellery', emoji: '💍' },
  { id: 'pottery', label: 'Pottery', emoji: '🏺' },
  { id: 'candles', label: 'Candles', emoji: '🕯️' },
  { id: 'art', label: 'Art & Posters', emoji: '🎨' },
  { id: 'handmade', label: 'Handmade', emoji: '🤲' },
  { id: 'clothing', label: 'Clothing', emoji: '👗' },
  { id: 'plants', label: 'Plants', emoji: '🌿' },
]

export const BBSR_LOCATIONS = [
  { id: 'kiit', label: 'KIIT Campus, Patia', area: 'Patia' },
  { id: 'patia', label: 'Patia Square, Bhubaneswar', area: 'Patia' },
  { id: 'infocity', label: 'Infocity Square, Bhubaneswar', area: 'Infocity' },
  {
    id: 'cspur',
    label: 'Chandrasekharpur, Bhubaneswar',
    area: 'Chandrasekharpur',
  },
  { id: 'saheed', label: 'Saheed Nagar, Bhubaneswar', area: 'Saheed Nagar' },
  { id: 'jaydev', label: 'Jaydev Vihar, Bhubaneswar', area: 'Jaydev Vihar' },
  { id: 'irc', label: 'IRC Village, Bhubaneswar', area: 'IRC Village' },
  {
    id: 'nandankanan',
    label: 'Nandankanan Road, Bhubaneswar',
    area: 'Nandankanan',
  },
  { id: 'rasulgarh', label: 'Rasulgarh, Bhubaneswar', area: 'Rasulgarh' },
  { id: 'bomikhal', label: 'Bomikhal, Bhubaneswar', area: 'Bomikhal' },
  { id: 'khandagiri', label: 'Khandagiri, Bhubaneswar', area: 'Khandagiri' },
  { id: 'baramunda', label: 'Baramunda, Bhubaneswar', area: 'Baramunda' },
  { id: 'vss', label: 'VSS Nagar, Bhubaneswar', area: 'VSS Nagar' },
  { id: 'acharya', label: 'Acharya Vihar, Bhubaneswar', area: 'Acharya Vihar' },
  { id: 'damana', label: 'Damana Square, Bhubaneswar', area: 'Damana' },
  { id: 'kalinga', label: 'Kalinga Nagar, Bhubaneswar', area: 'Kalinga Nagar' },
  { id: 'niladri', label: 'Niladri Vihar, Bhubaneswar', area: 'Niladri Vihar' },
  { id: 'pokhariput', label: 'Pokhariput, Bhubaneswar', area: 'Pokhariput' },
  { id: 'tamando', label: 'Tamando, Bhubaneswar', area: 'Tamando' },
  { id: 'mancheswar', label: 'Mancheswar, Bhubaneswar', area: 'Mancheswar' },
  {
    id: 'master',
    label: 'Master Canteen, Bhubaneswar',
    area: 'Master Canteen',
  },
  { id: 'unit4', label: 'Unit-4, Bhubaneswar', area: 'Unit-4' },
  { id: 'unit9', label: 'Unit-9, Bhubaneswar', area: 'Unit-9' },
  {
    id: 'kharvela',
    label: 'Kharvela Nagar, Bhubaneswar',
    area: 'Kharvela Nagar',
  },
  { id: 'forest', label: 'Forest Park, Bhubaneswar', area: 'Forest Park' },
  { id: 'dumduma', label: 'Dumduma, Bhubaneswar', area: 'Dumduma' },
]

export const STALLS: any[] = [
  {
    id: 's1',
    name: "Meera's Candle Corner",
    vendorId: 'v1',
    category: 'candles',
    location: 'KIIT Campus, Patia',
    locationId: 'kiit',
    rating: 4.8,
    reviewCount: 124,
    distance: '0.3 km',
    image: 'https://images.unsplash.com/photo-1602607702065-d22cf19ae99c?w=400',
    tags: ['Handmade', 'Aromatic', 'Custom'],
    isOpen: true,
    deliveryTime: '2-3 days',
    minOrder: 150,
  },
  {
    id: 's2',
    name: "Raj's Pottery Works",
    vendorId: 'v2',
    category: 'pottery',
    location: 'Patia Square, Bhubaneswar',
    locationId: 'patia',
    rating: 4.6,
    reviewCount: 89,
    distance: '0.5 km',
    image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400',
    tags: ['Traditional', 'Custom Order'],
    isOpen: true,
    deliveryTime: '3-5 days',
    minOrder: 250,
  },
  {
    id: 's3',
    name: "Priya's Jewel Box",
    vendorId: 'v3',
    category: 'jewellery',
    location: 'IRC Village, Bhubaneswar',
    locationId: 'irc',
    rating: 4.9,
    reviewCount: 203,
    distance: '0.8 km',
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400',
    tags: ['Silver', 'Gold Plated', 'Custom'],
    isOpen: false,
    deliveryTime: '1-2 days',
    minOrder: 300,
  },
  {
    id: 's4',
    name: 'Street Bites by Arjun',
    vendorId: 'v4',
    category: 'street-food',
    location: 'Saheed Nagar, Bhubaneswar',
    locationId: 'saheed',
    rating: 4.7,
    reviewCount: 512,
    distance: '1.1 km',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
    tags: ['Veg', 'Spicy', 'Fresh Daily'],
    isOpen: true,
    deliveryTime: '45 min',
    minOrder: 100,
  },
  {
    id: 's5',
    name: 'Canvas & Colors – Sunita',
    vendorId: 'v5',
    category: 'art',
    location: 'Jaydev Vihar, Bhubaneswar',
    locationId: 'jaydev',
    rating: 4.5,
    reviewCount: 67,
    distance: '2.0 km',
    image: 'https://images.unsplash.com/photo-1579762715118-a6f1d4b934f1?w=400',
    tags: ['Original Art', 'Prints', 'Custom'],
    isOpen: true,
    deliveryTime: '5-7 days',
    minOrder: 500,
  },
  {
    id: 's6',
    name: 'Green Thumb Plants',
    vendorId: 'v6',
    category: 'plants',
    location: 'Niladri Vihar, Bhubaneswar',
    locationId: 'niladri',
    rating: 4.4,
    reviewCount: 44,
    distance: '1.5 km',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400',
    tags: ['Indoor', 'Succulents', 'Rare'],
    isOpen: true,
    deliveryTime: '1 day',
    minOrder: 200,
  },
  {
    id: 's7',
    name: 'Infocity Chaat House',
    vendorId: 'v7',
    category: 'street-food',
    location: 'Infocity Square, Bhubaneswar',
    locationId: 'infocity',
    rating: 4.3,
    reviewCount: 211,
    distance: '0.2 km',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    tags: ['Veg', 'Quick Bites', 'Fresh'],
    isOpen: true,
    deliveryTime: '30 min',
    minOrder: 80,
  },
  {
    id: 's8',
    name: 'Damana Handloom House',
    vendorId: 'v8',
    category: 'clothing',
    location: 'Damana Square, Bhubaneswar',
    locationId: 'damana',
    rating: 4.6,
    reviewCount: 78,
    distance: '0.4 km',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    tags: ['Handloom', 'Sambalpuri', 'Cotton'],
    isOpen: true,
    deliveryTime: '2-3 days',
    minOrder: 400,
  },
  {
    id: 's9',
    name: 'Kalinga Krafts',
    vendorId: 'v9',
    category: 'handmade',
    location: 'Kalinga Nagar, Bhubaneswar',
    locationId: 'kalinga',
    rating: 4.7,
    reviewCount: 55,
    distance: '0.6 km',
    image: 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400',
    tags: ['Tribal Art', 'Handmade', 'Gifts'],
    isOpen: true,
    deliveryTime: '3-4 days',
    minOrder: 200,
  },
  {
    id: 's10',
    name: 'VSS Aroma Studio',
    vendorId: 'v10',
    category: 'candles',
    location: 'VSS Nagar, Bhubaneswar',
    locationId: 'vss',
    rating: 4.5,
    reviewCount: 39,
    distance: '0.7 km',
    image: 'https://images.unsplash.com/photo-1572726729207-a78d6feb18d7?w=400',
    tags: ['Soy Wax', 'Aromatic', 'Gifts'],
    isOpen: false,
    deliveryTime: '2-4 days',
    minOrder: 180,
  },
  {
    id: 's11',
    name: 'Khandagiri Terracotta',
    vendorId: 'v11',
    category: 'pottery',
    location: 'Khandagiri, Bhubaneswar',
    locationId: 'khandagiri',
    rating: 4.8,
    reviewCount: 91,
    distance: '0.3 km',
    image: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=400',
    tags: ['Terracotta', 'Traditional', 'Diyas'],
    isOpen: true,
    deliveryTime: '2-3 days',
    minOrder: 150,
  },
  {
    id: 's12',
    name: 'Mancheswar Momo Corner',
    vendorId: 'v12',
    category: 'street-food',
    location: 'Mancheswar, Bhubaneswar',
    locationId: 'mancheswar',
    rating: 4.4,
    reviewCount: 188,
    distance: '0.5 km',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400',
    tags: ['Momos', 'Veg & Non-Veg', 'Hot'],
    isOpen: true,
    deliveryTime: '20 min',
    minOrder: 60,
  },
  {
    id: 's13',
    name: 'Acharya Silver Works',
    vendorId: 'v13',
    category: 'jewellery',
    location: 'Acharya Vihar, Bhubaneswar',
    locationId: 'acharya',
    rating: 4.6,
    reviewCount: 62,
    distance: '0.4 km',
    image: 'https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=400',
    tags: ['Silver', 'Filigree', 'Custom'],
    isOpen: true,
    deliveryTime: '3-5 days',
    minOrder: 500,
  },
  {
    id: 's14',
    name: 'Forest Park Botanics',
    vendorId: 'v14',
    category: 'plants',
    location: 'Forest Park, Bhubaneswar',
    locationId: 'forest',
    rating: 4.3,
    reviewCount: 27,
    distance: '0.2 km',
    image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=400',
    tags: ['Indoor', 'Rare', 'Air Purifying'],
    isOpen: true,
    deliveryTime: '1 day',
    minOrder: 150,
  },
  {
    id: 's15',
    name: 'Rasulgarh Canvas',
    vendorId: 'v15',
    category: 'art',
    location: 'Rasulgarh, Bhubaneswar',
    locationId: 'rasulgarh',
    rating: 4.4,
    reviewCount: 33,
    distance: '0.6 km',
    image: 'https://images.unsplash.com/photo-1579762715118-a6f1d4b934f1?w=400',
    tags: ['Watercolor', 'Prints', 'Wall Art'],
    isOpen: true,
    deliveryTime: '4-6 days',
    minOrder: 350,
  },
]

export const PRODUCTS: Record<string, any[]> = {
  s1: [
    {
      id: 'p1',
      stallId: 's1',
      name: 'Lavender Dream Candle',
      price: 280,
      originalPrice: 350,
      image:
        'https://images.unsplash.com/photo-1572726729207-a78d6feb18d7?w=300',
      variants: ['Small', 'Medium', 'Large'],
      description: 'Hand-poured soy wax with real lavender buds.',
    },
    {
      id: 'p2',
      stallId: 's1',
      name: 'Rose & Sandalwood Candle',
      price: 320,
      originalPrice: null,
      image:
        'https://images.unsplash.com/photo-1602607702065-d22cf19ae99c?w=300',
      variants: ['Standard', 'Gift Box'],
      description: 'Perfect gift for loved ones.',
    },
    {
      id: 'p3',
      stallId: 's1',
      name: 'Custom Name Candle',
      price: 450,
      originalPrice: null,
      image: 'https://images.unsplash.com/photo-1543051932-6ef9fecfcb46?w=300',
      variants: [],
      description: 'Personalized with any name or message.',
    },
  ],
  s2: [
    {
      id: 'p4',
      stallId: 's2',
      name: 'Terracotta Mug',
      price: 180,
      originalPrice: 220,
      image:
        'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=300',
      variants: ['Natural', 'Painted'],
      description: 'Handcrafted terracotta mug.',
    },
    {
      id: 'p5',
      stallId: 's2',
      name: 'Flower Vase Set',
      price: 550,
      originalPrice: null,
      image:
        'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=300',
      variants: ['Small', 'Large', 'Set of 3'],
      description: 'Beautiful hand-painted vases.',
    },
  ],
  s3: [
    {
      id: 'p6',
      stallId: 's3',
      name: 'Oxidized Earrings',
      price: 199,
      originalPrice: 299,
      image:
        'https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=300',
      variants: ['Silver', 'Gold'],
      description: 'Trendy oxidized silver earrings.',
    },
    {
      id: 'p7',
      stallId: 's3',
      name: 'Beaded Anklet',
      price: 149,
      originalPrice: null,
      image:
        'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=300',
      variants: ['Single', 'Pair'],
      description: 'Handmade beaded anklet.',
    },
  ],
  s4: [
    {
      id: 'p8',
      stallId: 's4',
      name: 'Aloo Tikki Platter',
      price: 80,
      originalPrice: null,
      image:
        'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300',
      variants: ['4 pcs', '8 pcs'],
      description: 'Crispy aloo tikki with chutneys.',
    },
    {
      id: 'p9',
      stallId: 's4',
      name: 'Chaat Combo Box',
      price: 120,
      originalPrice: 150,
      image:
        'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=300',
      variants: ['Regular', 'Large'],
      description: 'Mix chaat combo for 2.',
    },
  ],
  s5: [
    {
      id: 'p10',
      stallId: 's5',
      name: 'Watercolor Landscape Print',
      price: 650,
      originalPrice: 800,
      image:
        'https://images.unsplash.com/photo-1579762715118-a6f1d4b934f1?w=300',
      variants: ['A4', 'A3'],
      description: 'Beautiful watercolor landscape.',
    },
    {
      id: 'p11',
      stallId: 's5',
      name: 'Custom Portrait',
      price: 1200,
      originalPrice: null,
      image:
        'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=300',
      variants: [],
      description: 'Hand-drawn portrait from your photo.',
    },
  ],
  s6: [
    {
      id: 'p12',
      stallId: 's6',
      name: 'Succulent Trio',
      price: 299,
      originalPrice: 399,
      image:
        'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=300',
      variants: ['With pot', 'Without pot'],
      description: 'Set of 3 mini succulents.',
    },
    {
      id: 'p13',
      stallId: 's6',
      name: 'Money Plant',
      price: 149,
      originalPrice: null,
      image:
        'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=300',
      variants: ['Small', 'Medium'],
      description: 'Classic money plant in a ceramic pot.',
    },
  ],
  s7: [
    {
      id: 'p14',
      stallId: 's7',
      name: 'Pani Puri Plate',
      price: 40,
      originalPrice: null,
      image:
        'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=300',
      variants: ['6 pcs', '12 pcs'],
      description: 'Crispy puris with tangy jaljeera water.',
    },
    {
      id: 'p15',
      stallId: 's7',
      name: 'Bhel Puri Box',
      price: 60,
      originalPrice: 80,
      image:
        'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300',
      variants: ['Regular', 'Spicy'],
      description: 'Light and crunchy bhel puri.',
    },
  ],
  s8: [
    {
      id: 'p16',
      stallId: 's8',
      name: 'Sambalpuri Saree',
      price: 1800,
      originalPrice: 2200,
      image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300',
      variants: ['Cotton', 'Silk'],
      description: 'Authentic hand-woven Sambalpuri saree.',
    },
    {
      id: 'p17',
      stallId: 's8',
      name: 'Ikat Dupatta',
      price: 450,
      originalPrice: null,
      image:
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=300',
      variants: ['Single', 'Set of 2'],
      description: 'Beautiful ikat pattern dupatta.',
    },
  ],
  s9: [
    {
      id: 'p18',
      stallId: 's9',
      name: 'Tribal Wall Art',
      price: 750,
      originalPrice: 900,
      image:
        'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=300',
      variants: ['Small', 'Large'],
      description: 'Hand-painted tribal motif wall art.',
    },
    {
      id: 'p19',
      stallId: 's9',
      name: 'Warli Gift Box',
      price: 350,
      originalPrice: null,
      image:
        'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=300',
      variants: [],
      description: 'Curated handmade gift set.',
    },
  ],
  s10: [
    {
      id: 'p20',
      stallId: 's10',
      name: 'Jasmine Soy Candle',
      price: 260,
      originalPrice: 320,
      image:
        'https://images.unsplash.com/photo-1572726729207-a78d6feb18d7?w=300',
      variants: ['Small', 'Large'],
      description: 'Pure soy wax with jasmine fragrance.',
    },
  ],
  s11: [
    {
      id: 'p21',
      stallId: 's11',
      name: 'Diya Set (12 pcs)',
      price: 120,
      originalPrice: 160,
      image:
        'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=300',
      variants: ['Painted', 'Plain'],
      description: 'Handmade terracotta diyas.',
    },
    {
      id: 'p22',
      stallId: 's11',
      name: 'Terracotta Planter',
      price: 280,
      originalPrice: null,
      image:
        'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=300',
      variants: ['Small', 'Medium', 'Large'],
      description: 'Eco-friendly terracotta planter.',
    },
  ],
  s12: [
    {
      id: 'p23',
      stallId: 's12',
      name: 'Veg Momo (8 pcs)',
      price: 80,
      originalPrice: null,
      image:
        'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=300',
      variants: ['Steamed', 'Fried'],
      description: 'Soft, juicy vegetable momos.',
    },
    {
      id: 'p24',
      stallId: 's12',
      name: 'Chicken Momo (8 pcs)',
      price: 100,
      originalPrice: null,
      image:
        'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=300',
      variants: ['Steamed', 'Fried', 'Pan-fried'],
      description: 'Tender chicken momos with chutney.',
    },
  ],
  s13: [
    {
      id: 'p25',
      stallId: 's13',
      name: 'Filigree Earrings',
      price: 650,
      originalPrice: 800,
      image:
        'https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=300',
      variants: ['Drop', 'Stud'],
      description: 'Intricate silver filigree work.',
    },
    {
      id: 'p26',
      stallId: 's13',
      name: 'Silver Bangle Set',
      price: 1200,
      originalPrice: null,
      image:
        'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=300',
      variants: ['Set of 2', 'Set of 4'],
      description: 'Pure silver traditional bangles.',
    },
  ],
  s14: [
    {
      id: 'p27',
      stallId: 's14',
      name: 'ZZ Plant',
      price: 350,
      originalPrice: 450,
      image:
        'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=300',
      variants: ['With pot', 'Without pot'],
      description: 'Low-maintenance indoor plant.',
    },
    {
      id: 'p28',
      stallId: 's14',
      name: 'Peace Lily',
      price: 280,
      originalPrice: null,
      image:
        'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=300',
      variants: ['Small', 'Medium'],
      description: 'Air-purifying peace lily.',
    },
  ],
  s15: [
    {
      id: 'p29',
      stallId: 's15',
      name: 'Odisha Landscape Print',
      price: 550,
      originalPrice: 700,
      image:
        'https://images.unsplash.com/photo-1579762715118-a6f1d4b934f1?w=300',
      variants: ['A4', 'A3'],
      description: 'Watercolor print of iconic Odisha scenery.',
    },
    {
      id: 'p30',
      stallId: 's15',
      name: 'Abstract Canvas',
      price: 900,
      originalPrice: null,
      image:
        'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=300',
      variants: ['12x16', '18x24'],
      description: 'Original abstract canvas painting.',
    },
  ],
}

export const TIME_SLOTS = [
  '9:00 AM - 11:00 AM',
  '11:00 AM - 1:00 PM',
  '1:00 PM - 3:00 PM',
  '3:00 PM - 5:00 PM',
  '5:00 PM - 7:00 PM',
]

export const MOCK_ORDERS = [
  {
    id: 'o1',
    product: 'Lavender Dream Candle',
    customer: 'Ananya S.',
    variant: 'Medium',
    qty: 2,
    total: 560,
    status: 'pending',
    time: '10 min ago',
    type: 'preorder',
    slot: '3:00 PM - 5:00 PM',
  },
  {
    id: 'o2',
    product: 'Custom Name Candle',
    customer: 'Rohit M.',
    variant: '-',
    qty: 1,
    total: 450,
    status: 'processing',
    time: '1 hr ago',
    type: 'immediate',
    slot: 'ASAP',
  },
  {
    id: 'o3',
    product: 'Rose & Sandalwood Candle',
    customer: 'Priya K.',
    variant: 'Gift Box',
    qty: 3,
    total: 960,
    status: 'ready',
    time: '3 hrs ago',
    type: 'preorder',
    slot: '11:00 AM - 1:00 PM',
  },
  {
    id: 'o4',
    product: 'Lavender Dream Candle',
    customer: 'Dev R.',
    variant: 'Small',
    qty: 1,
    total: 280,
    status: 'delivered',
    time: 'Yesterday',
    type: 'immediate',
    slot: 'ASAP',
  },
]
