export const CATEGORIES = [
  { id: 'all', label: 'All', emoji: '🏪' },
  { id: 'food', label: 'Food', emoji: '🍱' },
  { id: 'jewellery', label: 'Jewellery', emoji: '💎' },
  { id: 'candles', label: 'Candles', emoji: '🕯️' },
  { id: 'gifts', label: 'Gifts', emoji: '🎁' },
  { id: 'handicrafts', label: 'Handicrafts', emoji: '🏺' },
  { id: 'organic', label: 'Organic', emoji: '🌿' },
  { id: 'bakery', label: 'Bakery', emoji: '🥐' },
]

export const TIME_SLOTS = [
  '9:00 AM – 10:00 AM',
  '10:00 AM – 11:00 AM',
  '11:00 AM – 12:00 PM',
  '12:00 PM – 1:00 PM',
  '2:00 PM – 3:00 PM',
  '3:00 PM – 4:00 PM',
  '4:00 PM – 5:00 PM',
  '5:00 PM – 6:00 PM',
]

export const BBSR_LOCATIONS = [
  { id: 'kiit', label: 'KIIT Campus, Patia' },
  { id: 'cuttack', label: 'Cuttack Road' },
  { id: 'saheed', label: 'Saheed Nagar' },
  { id: 'master', label: 'Master Canteen' },
  { id: 'infocity', label: 'Infocity' },
  { id: 'nayapalli', label: 'Nayapalli' },
  { id: 'bhubaneswar', label: 'Old Town' },
]
export const SEED_STALLS = [
  // FOOD
  {
    id: 'seed_food_1',
    name: 'Maa ki Rasoi',
    category: 'food',
    location: 'KIIT Campus, Patia',
    description:
      'Home-cooked meals made with love. Dal, sabzi, roti, rice — just like home.',
    whatsapp: '+919876543210',
    openTime: '08:00',
    closeTime: '21:00',
    minOrder: '80',
    rating: 4.8,
    reviewCount: 124,
    isOpen: true,
    image:
      'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&q=80',
    tags: ['Homemade', 'Tiffin', 'Veg'],
    distance: '0.3 km',
    deliveryTime: '20–30 min',
  },
  {
    id: 'seed_food_2',
    name: 'Biryani Bros',
    category: 'food',
    location: 'Nandan Vihar, Bhubaneswar',
    description:
      'Authentic Hyderabadi dum biryani cooked in traditional handis. Chicken & Veg options.',
    whatsapp: '+919876543211',
    openTime: '12:00',
    closeTime: '22:00',
    minOrder: '150',
    rating: 4.7,
    reviewCount: 98,
    isOpen: true,
    image:
      'https://images.unsplash.com/photo-1563379091339-03246963d26d?w=600&q=80',
    tags: ['Biryani', 'Non-Veg', 'Spicy'],
    distance: '1.2 km',
    deliveryTime: '30–40 min',
  },
  {
    id: 'seed_food_3',
    name: 'Odia Tadka',
    category: 'food',
    location: 'Saheed Nagar, Bhubaneswar',
    description:
      'Traditional Odia thali with dalma, saga, macha curry and pakhala.',
    whatsapp: '+919876543212',
    openTime: '11:00',
    closeTime: '20:00',
    minOrder: '100',
    rating: 4.6,
    reviewCount: 76,
    isOpen: true,
    image:
      'https://images.unsplash.com/photo-1567337710282-00832b415979?w=600&q=80',
    tags: ['Odia', 'Thali', 'Traditional'],
    distance: '2.1 km',
    deliveryTime: '25–35 min',
  },

  // JEWELLERY
  {
    id: 'seed_jwl_1',
    name: 'Sunita Jewels',
    category: 'jewellery',
    location: 'Unit 4, Bhubaneswar',
    description:
      'Handcrafted silver and gold-plated jewellery. Jhumkas, necklaces, bangles and more.',
    whatsapp: '+919876543213',
    openTime: '10:00',
    closeTime: '19:00',
    minOrder: '200',
    rating: 4.9,
    reviewCount: 211,
    isOpen: true,
    image:
      'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80',
    tags: ['Silver', 'Handcrafted', 'Traditional'],
    distance: '1.5 km',
    deliveryTime: '1–2 days',
  },
  {
    id: 'seed_jwl_2',
    name: 'Meenakari Studio',
    category: 'jewellery',
    location: 'Janpath, Bhubaneswar',
    description:
      'Rajasthani meenakari jewellery, oxidised pieces, and tribal designs.',
    whatsapp: '+919876543214',
    openTime: '10:00',
    closeTime: '20:00',
    minOrder: '300',
    rating: 4.7,
    reviewCount: 88,
    isOpen: true,
    image:
      'https://images.unsplash.com/photo-1601121141461-9d6647bef0a4?w=600&q=80',
    tags: ['Meenakari', 'Oxidised', 'Tribal'],
    distance: '2.8 km',
    deliveryTime: '1–2 days',
  },

  // CANDLES
  {
    id: 'seed_candle_1',
    name: "Meera's Candle Corner",
    category: 'candles',
    location: 'Patia, Bhubaneswar',
    description:
      'Hand-poured soy wax candles with essential oils. Perfect for gifting and home décor.',
    whatsapp: '+919876543215',
    openTime: '09:00',
    closeTime: '19:00',
    minOrder: '150',
    rating: 4.9,
    reviewCount: 143,
    isOpen: true,
    image:
      'https://images.unsplash.com/photo-1602607919180-ace88d9f0dba?w=600&q=80',
    tags: ['Soy Wax', 'Aromatherapy', 'Gift'],
    distance: '0.8 km',
    deliveryTime: '2–4 hrs',
  },
  {
    id: 'seed_candle_2',
    name: 'Glow & Bloom',
    category: 'candles',
    location: 'IRC Village, Bhubaneswar',
    description:
      'Scented candles, reed diffusers and wax melts. All natural, no paraffin.',
    whatsapp: '+919876543216',
    openTime: '10:00',
    closeTime: '18:00',
    minOrder: '200',
    rating: 4.6,
    reviewCount: 67,
    isOpen: true,
    image:
      'https://images.unsplash.com/photo-1571781418606-70265b9cce90?w=600&q=80',
    tags: ['Natural', 'Reed Diffuser', 'Wax Melts'],
    distance: '3.2 km',
    deliveryTime: '3–5 hrs',
  },

  // GIFTS
  {
    id: 'seed_gift_1',
    name: 'The Gift Nook',
    category: 'gifts',
    location: 'Khandagiri, Bhubaneswar',
    description:
      'Personalised gifts, hampers and keepsakes for every occasion. Custom name engraving available.',
    whatsapp: '+919876543217',
    openTime: '10:00',
    closeTime: '20:00',
    minOrder: '250',
    rating: 4.8,
    reviewCount: 190,
    isOpen: true,
    image:
      'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80',
    tags: ['Personalised', 'Hamper', 'Custom'],
    distance: '4.1 km',
    deliveryTime: '1–2 days',
  },
  {
    id: 'seed_gift_2',
    name: 'Wrapped With Love',
    category: 'gifts',
    location: 'Chandrasekharpur, Bhubaneswar',
    description:
      'Curated gift boxes for birthdays, anniversaries and festivals. Eco-friendly packaging.',
    whatsapp: '+919876543218',
    openTime: '09:00',
    closeTime: '19:00',
    minOrder: '300',
    rating: 4.5,
    reviewCount: 55,
    isOpen: true,
    image:
      'https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=600&q=80',
    tags: ['Gift Box', 'Eco-friendly', 'Festival'],
    distance: '5.0 km',
    deliveryTime: '1–2 days',
  },

  // HANDICRAFTS
  {
    id: 'seed_craft_1',
    name: 'Tribal Craft Hub',
    category: 'handicrafts',
    location: 'Ekamra Haat, Bhubaneswar',
    description:
      'Authentic Odia handicrafts — Pattachitra, Dhokra, Sabai grass products and more.',
    whatsapp: '+919876543219',
    openTime: '09:00',
    closeTime: '19:00',
    minOrder: '200',
    rating: 4.9,
    reviewCount: 302,
    isOpen: true,
    image:
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    tags: ['Pattachitra', 'Dhokra', 'Handmade'],
    distance: '3.5 km',
    deliveryTime: '1–3 days',
  },
  {
    id: 'seed_craft_2',
    name: 'Clay & Canvas',
    category: 'handicrafts',
    location: 'Nayapalli, Bhubaneswar',
    description: 'Hand-painted pottery, terracotta décor and custom wall art.',
    whatsapp: '+919876543220',
    openTime: '10:00',
    closeTime: '18:00',
    minOrder: '150',
    rating: 4.7,
    reviewCount: 112,
    isOpen: true,
    image:
      'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&q=80',
    tags: ['Pottery', 'Terracotta', 'Wall Art'],
    distance: '2.9 km',
    deliveryTime: '2–4 hrs',
  },

  // ORGANIC
  {
    id: 'seed_organic_1',
    name: 'Green Roots Farm',
    category: 'organic',
    location: 'Mancheswar, Bhubaneswar',
    description:
      'Farm-fresh organic vegetables, fruits, honey and cold-pressed oils. Delivered same day.',
    whatsapp: '+919876543221',
    openTime: '06:00',
    closeTime: '18:00',
    minOrder: '100',
    rating: 4.8,
    reviewCount: 178,
    isOpen: true,
    image:
      'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&q=80',
    tags: ['Organic', 'Farm Fresh', 'No Pesticides'],
    distance: '6.2 km',
    deliveryTime: '2–4 hrs',
  },
  {
    id: 'seed_organic_2',
    name: 'Honey & Spice',
    category: 'organic',
    location: 'Pokhariput, Bhubaneswar',
    description:
      'Raw forest honey, organic spices, herbal teas and natural skincare products.',
    whatsapp: '+919876543222',
    openTime: '08:00',
    closeTime: '20:00',
    minOrder: '150',
    rating: 4.6,
    reviewCount: 94,
    isOpen: true,
    image:
      'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&q=80',
    tags: ['Honey', 'Spices', 'Herbal'],
    distance: '4.8 km',
    deliveryTime: '3–5 hrs',
  },

  // BAKERY
  {
    id: 'seed_bake_1',
    name: 'Bake Street',
    category: 'bakery',
    location: 'Acharya Vihar, Bhubaneswar',
    description:
      'Artisan breads, croissants, pastries and custom cakes baked fresh every morning.',
    whatsapp: '+919876543223',
    openTime: '07:00',
    closeTime: '20:00',
    minOrder: '100',
    rating: 4.9,
    reviewCount: 256,
    isOpen: true,
    image:
      'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80',
    tags: ['Artisan', 'Custom Cakes', 'Sourdough'],
    distance: '1.8 km',
    deliveryTime: '1–2 hrs',
  },
  {
    id: 'seed_bake_2',
    name: 'Sweet Tooth Studio',
    category: 'bakery',
    location: 'Rajmahal Square, Bhubaneswar',
    description:
      'Belgian chocolate cakes, macarons, brownies and festive sweets. Order 24hrs in advance.',
    whatsapp: '+919876543224',
    openTime: '09:00',
    closeTime: '21:00',
    minOrder: '200',
    rating: 4.8,
    reviewCount: 167,
    isOpen: true,
    image:
      'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80',
    tags: ['Chocolate', 'Macarons', 'Custom'],
    distance: '2.4 km',
    deliveryTime: '2–3 hrs',
  },
]
// export const SEED_STALLS = [
//   {
//     name: "Meera's Candle Corner",
//     category: 'candles',
//     location: 'KIIT Campus, Patia',
//     description: 'Hand-poured soy candles with natural fragrances.',
//     whatsapp: '9876543210',
//     openTime: '09:00',
//     closeTime: '20:00',
//     minOrder: '150',
//     vendorId: 'seed',
//     rating: 4.8,
//     reviewCount: 124,
//     isOpen: true,
//     image: 'https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=400',
//     tags: ['Soy Wax', 'Handmade', 'Gift'],
//     distance: '0.5 km',
//     deliveryTime: '30–45 min',
//   },
//   {
//     name: 'The Clay Studio',
//     category: 'pottery',
//     location: 'Saheed Nagar',
//     description: 'Handcrafted pottery and ceramic art pieces.',
//     whatsapp: '9876543211',
//     openTime: '10:00',
//     closeTime: '19:00',
//     minOrder: '200',
//     vendorId: 'seed',
//     rating: 4.6,
//     reviewCount: 89,
//     isOpen: true,
//     image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400',
//     tags: ['Ceramic', 'Handcrafted', 'Home Decor'],
//     distance: '1.2 km',
//     deliveryTime: '45–60 min',
//   },
//   {
//     name: 'Street Bites',
//     category: 'street-food',
//     location: 'Master Canteen',
//     description: 'Authentic Odia street food — chhena poda, dahi bara, more.',
//     whatsapp: '9876543212',
//     openTime: '08:00',
//     closeTime: '22:00',
//     minOrder: '80',
//     vendorId: 'seed',
//     rating: 4.9,
//     reviewCount: 312,
//     isOpen: true,
//     image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
//     tags: ['Odia', 'Street Food', 'Snacks'],
//     distance: '0.8 km',
//     deliveryTime: '20–30 min',
//   },
//   {
//     name: 'GreenThumb Plants',
//     category: 'plants',
//     location: 'Nayapalli',
//     description: 'Indoor plants, succulents and custom planters.',
//     whatsapp: '9876543213',
//     openTime: '09:00',
//     closeTime: '18:00',
//     minOrder: '100',
//     vendorId: 'seed',
//     rating: 4.7,
//     reviewCount: 67,
//     isOpen: false,
//     image: 'https://images.unsplash.com/photo-1463936575829-25148e1db1b8?w=400',
//     tags: ['Indoor', 'Succulents', 'Gift'],
//     distance: '2.1 km',
//     deliveryTime: '60–90 min',
//   },
//   {
//     name: 'Sparkle Jewels',
//     category: 'jewellery',
//     location: 'Infocity',
//     description: 'Handmade silver and beaded jewellery.',
//     whatsapp: '9876543214',
//     openTime: '11:00',
//     closeTime: '20:00',
//     minOrder: '250',
//     vendorId: 'seed',
//     rating: 4.5,
//     reviewCount: 43,
//     isOpen: true,
//     image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400',
//     tags: ['Silver', 'Handmade', 'Custom'],
//     distance: '3.4 km',
//     deliveryTime: '45–60 min',
//   },
//   {
//     name: 'Rang De Art',
//     category: 'art',
//     location: 'Old Town',
//     description: 'Watercolor and acrylic paintings, custom portraits.',
//     whatsapp: '9876543215',
//     openTime: '10:00',
//     closeTime: '19:00',
//     minOrder: '300',
//     vendorId: 'seed',
//     rating: 4.9,
//     reviewCount: 55,
//     isOpen: true,
//     image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=400',
//     tags: ['Watercolor', 'Portraits', 'Custom'],
//     distance: '4.0 km',
//     deliveryTime: 'Pickup only',
//   },
// ]

export const TIME_ZONE = 'Asia/Kolkata'
export const MOCK_ORDERS: any[] = []
export const MOCK_WISHLIST: any[] = []
export const MOCK_REVIEWS: any[] = []
export const STALLS: any[] = []
export const PRODUCTS: Record<string, any[]> = {}
